services:
  event_service:
    build: ./event_service
    ports:
      - "50051"
    deploy:
      replicas: 3
    depends_on:
      - event_db
  event_db:
    image: postgres
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
      POSTGRES_DB: eventdb
  user_service:
    build: ./user_service
    ports:
      - "50052"
    deploy:
      replicas: 3
    depends_on:
      - user_db
  user_db:
    image: postgres
    environment:
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: userdb
  gateway:
    build: ./gateway
    ports:
      - "5001:5000"
    depends_on:
      - event_service
      - user_service
  service_discovery:
    build: ./service_discovery
    ports:
      - "8000:8000"
